package msgdef

// InitBytesMsg 初始字节流消息
func (def *MsgDef) InitBytesMsg() {
	def.RegMsg(ClientVertifyReqMsgID, new(ClientVertifyReq))
	def.RegMsg(ClientVertifySucceedRetMsgID, new(ClientVertifySucceedRet))
	def.RegMsg(ClientVertifyFailedRetMsgID, new(ClientVertifyFailedRet))
	def.RegMsg(HeartBeatMsgID, new(HeartBeat))

	def.RegMsg(EntitySrvInfoNotifyID, new(EntitySrvInfoNotify))
	//def.RegMsg(SessionNotifyID, new(SessionNotify))
	//def.RegMsg(SessionCreateID, new(SessionCreate))
	//def.RegMsg(ClientVertifySucceedMsgID, new(ClientVertifySucceed))
	def.RegMsg(ProtoSyncMsgID, new(ProtoSync))
	def.RegMsg(ClientFrameMsgID, new(ClientFrameMsg))
	def.RegMsg(ServerFrameMsgID, new(ServerFrameMsg))
	def.RegMsg(FramesMsgID, new(FramesMsg))
	def.RegMsg(RequireFramesMsgID, new(RequireFramesMsg))
	def.RegMsg(PropsSyncMsgID, new(PropsSync))
	def.RegMsg(PropsSyncClientMsgID, new(PropsSyncClient))
	def.RegMsg(MRolePropsSyncClientMsgID, new(MRolePropsSyncClient))
	def.RegMsg(EnterCellReqMsgID, new(EnterCellReq))
	def.RegMsg(LeaveCellReqMsgID, new(LeaveCellReq))
	def.RegMsg(EnterAOIMsgID, new(EnterAOI))
	def.RegMsg(LeaveAOIMsgID, new(LeaveAOI))
	//def.RegMsg(AOIPosChangeMsgID, new(AOIPosChange))
	def.RegMsg(EnterCellMsgID, new(EnterCell))
	def.RegMsg(LeaveCellMsgID, new(LeaveCell))
	//def.RegMsg(UserMoveMsgID, new(UserMove))
	//def.RegMsg(EntityPosSetMsgID, new(EntityPosSet))
	def.RegMsg(CellEntityMsgID, new(CellEntityMsg))
	def.RegMsg(ClientTransportMsgID, new(ClientTransport))
	def.RegMsg(CreateEntityReqMsgID, new(CreateEntityReq))
	def.RegMsg(CreateEntityRetMsgID, new(CreateEntityRet))
	def.RegMsg(DestroyEntityReqMsgID, new(DestroyEntityReq))
	def.RegMsg(DestroyEntityRetMsgID, new(DestroyEntityRet))
	def.RegMsg(EntityMsgTransportMsgID, new(EntityMsgTransport))
	def.RegMsg(EntityMsgChangeMsgID, new(EntityMsgChange))
	def.RegMsg(SrvMsgTransportMsgID, new(SrvMsgTransport))
	def.RegMsg(TestBinMsgID, new(TestBinMsg))
	def.RegMsg(RPCMsgID, new(RPCMsg))
	def.RegMsg(UserDuplicateLoginNotifyMsgID, new(UserDuplicateLoginNotify))

	def.RegMsg(SyncClockMsgID, new(SyncClock))

	def.RegMsg(SpaceUserConnectMsgID, new(SpaceUserConnect))
	def.RegMsg(SpaceUserConnectSucceedRetMsgID, new(SpaceUserConnectSucceedRet))
	def.RegMsg(SyncUserStateMsgID, new(SyncUserState))
	def.RegMsg(AOISyncUserStateMsgID, new(AOISyncUserState))
	def.RegMsg(AdjustUserStateMsgID, new(AdjustUserState))
	def.RegMsg(EntityAOISMsgID, new(EntityAOIS))
	def.RegMsg(EntityEventMsgID, new(EntityEvent))

	def.RegMsg(CreateGhostReqMsgID, new(CreateGhostReq))
	def.RegMsg(DeleteGhostReqMsgID, new(DeleteGhostReq))
	def.RegMsg(TransferRealReqMsgID, new(TransferRealReq))
	def.RegMsg(NewRealNotifyMsgID, new(NewRealNotify))
}
